name: LittleBiomes
main: net.lumamc.biomes.LittleBiomes
version: '1.0-SNAPSHOT'
api-version: 1.21
depend:
  - ProtocolLib
commands:
  littlebiomes:
    description: Main command for LittleBiomes plugin.
    usage: /<command>