name: LittleBiomes
main: dev.lumas.biomes.LittleBiomes
version: '1.0-SNAPSHOT'
api-version: 1.21
softdepend:
  - RealisticSeasons
  - WorldGuard
depend:
  - ProtocolLib
commands:
  littlebiomes:
    description: Main command for LittleBiomes plugin.
    usage: /<command>